-- Task 3: GroupBy, Aggregate Functions, Having, Order By, where
=================================================================

-- 14. Find the total number of couriers handled by each employee.

alter table Couriers
add EmployeeID int;

select e.EmployeeID, e.Name as EmployeeName, COUNT(c.CourierID) as TotalCouriersHandled
from Employees e
left join Couriers c ON e.EmployeeID = c.EmployeeID  
group by e.EmployeeID, e.Name;

-- 15. Calculate the total revenue generated by each location

select l.LocationID, l.LocationName, sum(p.Amount) as TotalRevenue 
from Location l 
join Payment p on l.LocationID = p.LocationId 
group by l.LocationID, l.LocationName;

-- 16. Find the total number of couriers delivered to each location. 

select l.LocationID, l.LocationName, COUNT(c.CourierID) as TotalCouriersDelivered
from Location l 
join Payment p on l.LocationID = p.LocationId
join Couriers c on p.CourierID = c.CourierID
where c.Status = 'Delivered'
group by l.LocationID,l.LocationName;

-- 17. Find the courier with the highest average delivery time

select top 1 CourierID,SenderName,ReceiverName, AVG(DATEDIFF(DAY,SentDate,DeliveryDate)) as AvgDeliveryTime
from Couriers 
where Status = 'Delivered'
group by CourierID, SenderName, ReceiverName
order by AvgDeliveryTime desc;

-- 18. Find Locations with Total Payments Less Than a Certain Amount

select l.locationID, l.locationName,sum(p.Amount) as TotalPayments
from Location l 
join Payment p
on l.LocationID = p.LocationId
group by l.LocationID,l.LocationName
having SUM(p.Amount) < 1000;

-- 19. Calculate Total Payments per Location

select l.locationID, l.locationName,sum(p.Amount) as TotalPayments
from Location l 
join Payment p
on l.LocationID = p.LocationId
group by l.LocationID,l.LocationName;

-- 20. Retrieve couriers who have received payments totaling more than 1000 in a specific location (LocationID = X) 

select c.CourierID, c.SenderName, c.ReceiverName, SUM(p.Amount) as TotalPayments
from Couriers c
join Payment p ON c.CourierID = p.CourierID
join Location l ON p.LocationID = l.LocationID
where l.LocationID = 4
group by c.CourierID, c.SenderName, c.ReceiverName
having sum(p.Amount) > 1000;

--  21. Retrieve couriers who have received payments totaling more than 1000 after a certain date (PaymentDate > 'YYYY-MM-DD')

select c.CourierID, c.SenderName, c.ReceiverName, SUM(p.Amount) as TotalPayments
from Couriers c
join Payment p ON c.CourierID = p.CourierID
where p.PaymentDate > '2024-09-10'
group by c.CourierID, c.SenderName, c.ReceiverName
having sum(p.Amount) > 1000 ;

-- 22. Retrieve locations where the total amount received is more than 5000 before a certain date (PaymentDate > 'YYYY-MM-DD')

select l.LocationID, l.LocationName, SUM(p.Amount) as TotalPayments
from Location l
join Payment p ON l.LocationID = p.LocationId
where p.PaymentDate < '2024-09-10'
group by l.LocationID,l.LocationName
having sum(p.Amount) > 5000; 